.SILENT:

VMFILES = info.gif infobutton.tcl pkgIndex.tcl
VMVERSION = 1.0
DIR = $(PLUGINDIR)/noarch/tcl/infobutton$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying infobutton $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
