.SILENT:

VMFILES = pkgIndex.tcl structurecheck.tcl

VMVERSION = 1.2
DIR = $(PLUGINDIR)/noarch/tcl/structurecheck$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying structurecheck $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
