.SILENT:

TKCONFILES = vmdtkcon.tcl tkcon-modified.tcl pkgIndex.tcl README
DIR = $(PLUGINDIR)/noarch/tcl/vmdtkcon2.0

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib: 
	@echo "Copying vmdtkcon 2.0 files to $(DIR)"
	mkdir -p $(DIR) 
	cp -rf $(TKCONFILES) $(DIR) 
